### ISSUE TITLE
[BUG] Swagger page returns 404

### ISSUE THREAD

**Issue by dancamdev** [aaronleopold/stump#104]
**Describe the bug**
Trying to get to the `swagger-ui` page as described in the docs returns with a 404 page.

**To Reproduce**
Go to `http(s)://your-server(:10801)/swagger-ui`

**Expected behavior**
Show the Swagger API page

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS (Safari) + Docker Stump instance

**Additional context**

I've explicitly set the `ENABLE_SWAGGER_UI ` to `true` just to make sure.

```
r@http://192.168.178.192:10801/assets/FourOhFour.a5712a44.js:1:57 Ox@http://192.168.178.192:10801/assets/index.407e6789.js:30:19537 Yy@http://192.168.178.192:10801/assets/index.407e6789.js:32:3175 CL@http://192.168.178.192:10801/assets/index.407e6789.js:32:44933 kL@http://192.168.178.192:10801/assets/index.407e6789.js:32:40044 DN@http://192.168.178.192:10801/assets/index.407e6789.js:32:39972 Ah@http://192.168.178.192:10801/assets/index.407e6789.js:32:39826 l1@http://192.168.178.192:10801/assets/index.407e6789.js:32:36161 yL@http://192.168.178.192:10801/assets/index.407e6789.js:32:35109 yL@[native code] C@http://192.168.178.192:10801/assets/index.407e6789.js:17:1582 B@http://192.168.178.192:10801/assets/index.407e6789.js:17:1946
```

**Comment by aaronleopold** [comment]
Hey there, thanks for the report! Can you confirm the registry/tag of the image, as well? I recently put a sunset notice on the `aaronleopold/stump-preview` repo, as the `nightly` tag moving forward will live in `aaronleopold/stump`, but haven't had a chance to update the documentation website to reflect this. Based on the PR merge timestamp for swagger, and the last image push date on `aaronleopold/stump-preview`, I wanted to check that you actually have an image with the swagger changes.

**Comment by dancamdev** [comment]
uh that is it. sorry I didn't catch that. I'm closing this issue then.

**Comment by aaronleopold** [comment]
No worries at all! The lag between features/updates and documentation updates is bound to cause some confusions. If you face the same issue after updating the tag feel free to reopen the issue

**Comment by aaronleopold** [comment]
Can you try setting `ENABLE_SWAGGER_UI=true` in your `environment` of your compose? Swagger is off by default, which perhaps should just change in the future.

**Comment by dancamdev** [comment]
I did enable it explicitly, no luck though. It is working when running it locally as I mentioned on Discord. There must be something wrong with my `docker-compose`

Is it correct to expose only port 10801 like so?

```
    ports:
      - 10801:10801 
```

**Comment by dancamdev** [comment]
Let me close this for now, as a recent update of the docker image seems to have fixed this issue I had.

**Comment by ecraven** [comment]
Unfortunately I seem to have the same problem, I'm using 0.0.9 (also tried latest), I've set `ENABLE_SWAGGER_UI`, no dice :-/

**Comment by ecraven** [comment]
Sorry for the noise, everything works perfectly, not sure what the problem was :-/
