### ISSUE TITLE
localization / language support

### ISSUE THREAD

**Issue by aaronleopold** [aaronleopold/stump#106]
I've started to hone the locale `json` file structure for English, something that just has to get done before any other languages are supported (so the `json` files keys are 1:1).

Currently, this work is being done in [al/bye-chakra](https://github.com/aaronleopold/stump/tree/al/bye-chakra) branch, specifically the locale files [here](https://github.com/aaronleopold/stump/tree/al/bye-chakra/packages/interface/src/i18n/locales).

Once `en.json` (English) is completed, I think I will just mass translate that file to a handful of other languages using whatever AI is best suited for language processing. I'll start with languages that use alphabets I am personally familiar with (e.g. Spanish, French, Italian, etc) and potentially add a few with alphabets I am not / those without alphabets (e.g. Russian,  Chinese, Japanese, etc). This should kickstart the language support, but as with most AI things these translations will need to be checked by someone who *actually* knows the language.

**Comment by iEusKid** [comment]
if you want to translate it to Arabic i will help you with that

**Comment by aaronleopold** [comment]
> if you want to translate it to Arabic i will help you with that

That would be awesome, thank you! You're welcome to start whenever, basing off of [this en.json](https://github.com/aaronleopold/stump/blob/al/bye-chakra/packages/interface/src/i18n/locales/en.json) as a base, but keep in mind it has some missing keys. 

I'd be happy to ping you once the file itself is more completed, as well. I'm trying to look into self hostable services that provide some sort of web UI for people to do the translations, too, since it's all manual JSON editing at this point.

**Comment by iEusKid** [comment]
> > if you want to translate it to Arabic i will help you with that
> 
> That would be awesome, thank you! You're welcome to start whenever, basing off of [this en.json](https://github.com/aaronleopold/stump/blob/al/bye-chakra/packages/interface/src/i18n/locales/en.json) as a base, but keep in mind it has some missing keys.
> 
> I'd be happy to ping you once the file itself is more completed, as well. I'm trying to look into self hostable services that provide some sort of web UI for people to do the translations, too, since it's all manual JSON editing at this point.

no problem, i started with it. also started stump docker container but didn't see any en.json there ( i want to replace it to see the translation)

**Comment by aaronleopold** [comment]
Honestly I'm not sure where the locale files would be visible in the container, it must be somewhere inside that web bundle I believe is at `/app/client`. But, the currently nightly is based off of the `develop` branch, and much of the locale changes and updated usages are in `al/by-chakra`, so until that gets merged or I push an image manually based off of that work it will be hard to preview it in Stump

**Comment by aaronleopold** [comment]
Superseded by #139
