### ISSUE TITLE
Cross compilation (Docker) to arm64 and arm/v7

### ISSUE THREAD

**Issue by aaronleopold** [aaronleopold/stump#21]
Making this a real issue to hopefully get more visibility. I haven't quite figured out how to get cross-compilation (in Docker) working, an absolutely essential thing to get working so Stump can run on arm systems (e.g. rpi-4).

see https://github.com/aaronleopold/stump/tree/aleopold--arm64-can-sma

**Comment by aaronleopold** [comment]
same thing will need to be figured out for linux/arm/v7 too

**Comment by alxjpzmn** [comment]
Have you tried [Cross](https://github.com/cross-rs/cross#docker-in-docker)? Any objections of adding it to the project? If not, I'd give it a go later today.

**Comment by aaronleopold** [comment]
I'm definitely open to trying it! Feel free to give it a go, I did add `openssl` for arm64 in the [Cargo.toml](https://github.com/aaronleopold/stump/blob/aleopold--arm64-can-sma/core/Cargo.toml#L44) but it'll have to be added for each other target.

**Comment by aaronleopold** [comment]
Reopening this as compiation is successful for both arm64 and arm/v7, however testing on actual arm devices fails. I spent quite some time trying to figure this out and haven't gotten it yet. At first I thought maybe the build wasn't actually being statically compiled, but enforcing that didn't work. I added binutils in the final stage for debugging and found this:

```bash
/app $ readelf -a stump | grep interpreter
      [Requesting program interpreter: /lib/ld-linux-aarch64.so.1]

/lib $ ls
apk                     libc.musl-aarch64.so.1  libz.so.1.2.12
firmware                libcrypto.so.1.1        mdev
ld-musl-aarch64.so.1    libssl.so.1.1           modules-load.d
libapk.so.3.12.0        libz.so.1               sysctl.d
```

Looks like it is trying to grab something that doesn't exist

**Comment by aaronleopold** [comment]
This line https://github.com/aaronleopold/stump/blob/develop/Dockerfile#L115 fixes the docker image for arm64, now I will just have to fix arm/v7 and can close this issue.

**Comment by aaronleopold** [comment]
Closing for https://github.com/aaronleopold/stump/issues/27
