### ISSUE TITLE
Scanner not detecting books in root folder

### ISSUE THREAD

**Issue by Chizi123** [aaronleopold/stump#39]
For files in the root folder (i.e. the folder where the top of the library is located), files not in folders are not being included in the scan.
I am unsure if this is intended or unintended behavior, but for someone with a non-standard file ordering, this is limiting for the utility of stump.

I would hope that the scanner would find all acceptable files in the library and display them as available.

**Comment by aaronleopold** [comment]
@Chizi123 thanks for the report! This is unintended, I just didn't account for that library structure.

**Comment by aaronleopold** [comment]
The fix for this went into the `develop` branch, I tested it briefly and it seemed to work. I'll test a little more thoroughly this weekend, but will keep this issue open until it is in main.
