### ISSUE TITLE
Implement appropriate application navigation system

### ISSUE THREAD

**Issue by aaronleopold** [aaronleopold/stump#45]
Navigation is really not ideal right now. The nav icons mimic the native browser navigation, but that is incorrect.

If I am at `/books/:id/pages/:page` and I go backward, it should take me to `/books/:id`, not the literal previous history (which might just be the previous page).

If I am on `/books/:id`, going backward should take me to `/series/:id`, etc

**Comment by dancamdev** [comment]
If you don't mind me looking into this, I cloned the repo and it's working locally!

To clarify, since this is going to be my very first task on this project, is the issue only related to the browser 'go back' functionality? Anything else I should be keeping in mind?

For example, I've seen the interface is shared on desktop apps as well, do you expect `react-router` to handle the fix correctly on desktop as well?

**Comment by aaronleopold** [comment]
I **don't** mind at all! Pretty much any issue is fair game if someone wants to contribute.

> is the issue only related to the browser 'go back' functionality? Anything else I should be keeping in mind?

I can't think of an example where moving forward would require something other than native, because once backward is corrected forward should also be correct (I think). This fix really only applies to the `NavigationButtons` embeded in the `SideBar`:

<img width="379" alt="Screenshot 2023-03-20 at 4 23 37 PM" src="https://user-images.githubusercontent.com/36278431/226486897-4ab2b4d2-8fc2-494e-85ad-cbfb4ae05102.png">

I think one stipulation could be if someone had this sort of history:

- `/`
- `/libraries/id`
- `/series/id`
- `/series/id?page=25`
- `/books/id`
- `/books/id/pages/5`

It would be *nice* if going backward from `/books/id` retained the `?page=25` param for `/series/id`, but that might be complicated depending on implementation and I'm not overly worried about it for now.

> Anything else I should be keeping in mind?
>
> For example, I've seen the interface is shared on desktop apps as well, do you expect react-router to handle the fix correctly on desktop as well?

Honestly I've found that there are very few things that don't have 100% compatibility between web and desktop, they use the same React component, so I doubt there will be an issue when it comes time for a desktop release. However, yes - I would expect the fix to properly work in desktop as well. That being said, desktop isn't and won't be a priority of mine until *after* an initial release and bug-fix phase.

**Comment by dancamdev** [comment]
Hey @aaronleopold, I've been playing around with the top bar navigation buttons and here's a couple of thoughts.

I understand you're thinking of it similarly to a file-system approach with directories and sub directories, where 'going back' actually means going to the parent directory.

This is reflected by this flow and behaviour: `home` -> *clicks on book* -> `/book/id` -> *clicks top bar back button* -> `series/id`.

From a UX POV, I'd expect the top bar back button to get me back to `home` instead. This also introduces inconsistencies with the browser history and the browsers' navigation buttons behaviour. Which is not desirable IMO.

So now I'm beginning to wonder whether the `NavigationButtons` are needed at all or if they should just reflect the browser navigation button functionality to have it available on the Desktop app. Thoughts?

**Comment by aaronleopold** [comment]
Thanks so much for your thoughtful insights! I think you made really solid points. 

> they should just reflect the browser navigation button functionality to have it available on the Desktop app

I think for the time being we can update those buttons to match your description: hidden unless desktop, mimicking native browser forward/backwards navigation

**Comment by dancamdev** [comment]
Great, do we have an environment variable or something that can tell me if the app is running on electron and therefore should show the buttons?

**Comment by aaronleopold** [comment]
It actually doesn't use Electron, but [this shorthand hook](https://github.com/aaronleopold/stump/blob/develop/packages/client/src/context.ts#L34) should get you what you need. In case its helpful, [here is an example usage](https://github.com/aaronleopold/stump/blob/bb67ec2105655fdc3219fd5d86ba997c8ac960b7/packages/interface/src/AppLayout.tsx#L89)

**Comment by dancamdev** [comment]
Here's the error:

> Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './pages/Home.jsx'? ts(2835)

Also found this [issue discussing this](https://github.com/microsoft/TypeScript/issues/49083) - it looks like it's one of those weird things you gotta live with because JS exists

**Comment by aaronleopold** [comment]
Resolved by #108, thanks again @dancamdev!
