### ISSUE TITLE
Design home page

### ISSUE THREAD

**Issue by aaronleopold** [aaronleopold/stump#49]
the homepage needs some TLC. In general, should display:

- Keep reading (books with progress that aren't fully complete)
- user statistics (read books, read authors, idk what else)

Should have some sort of group of empty states:

- new server (i.e. no libraries configured)
- no media (i.e. library doesn't have any series/media inside)

Design contributions, without code, are also acceptable for hacktoberfest.

### Inspiration

![Image](https://user-images.githubusercontent.com/36278431/168447303-7b7adc8a-62d5-45d5-9408-95ab8c007b1a.png)

**Comment by crsdvaibhav** [comment]
Hey @aaronleopold I would like to work on this issue, could you assign it to me?

**Comment by aaronleopold** [comment]
Hi @crsdvaibhav, no problem - thanks!

**Comment by aaronleopold** [comment]
> Hey @aaronleopold, is it possible for me to work on this issue too?

Hey @Mango04, were you wanting to do just design work or actually coding the changes? I am not sure what @crsdvaibhav has done or plans to work on, but I don't see too much of an issue with it and seeing what ideas each has. 

I would say if you both do coding contributions, make a separate component for the home screen to reduce the chances of conflicts on merge.

**Comment by Mango04** [comment]
> > Hey @aaronleopold, is it possible for me to work on this issue too?
> 
> Hey @Mango04, were you wanting to do just design work or actually coding the changes? I am not sure what @crsdvaibhav has done or plans to work on, but I don't see too much of an issue with it and seeing what ideas each has.
> 
> I would say if you both do coding contributions, make a separate component for the home screen to reduce the chances of conflicts on merge.

Hi, I am interested in designing the front end of the homepage.

**Comment by Mango04** [comment]
Hi, I am interested in designing the front end of the homepage.

**Comment by aaronleopold** [comment]
Any updates on this task? @crsdvaibhav or @Mango04?

**Comment by aaronleopold** [comment]
Closing tracking for this in favor of https://github.com/aaronleopold/stump/issues/107
