### ISSUE TITLE
Design book overview page

### ISSUE THREAD

**Issue by aaronleopold** [aaronleopold/stump#52]
The book overview page is the page located at `books/:id`

In general, it should display the following:

- [x] Book thumbnail
- [ ] Buttons to navigate to reading the media
    - [ ] If progress exists, and book isn't completed, enable `Continue Reading` button
    - [ ] `Start Reading` button that goes to first page
- [ ] Download icon button
- [ ] Display metadata
    - [ ] associated tags
    - [ ] file status
    - [ ] other meta (e.g file attributes, doesn't currently have much else currently)

At this point I'm not sure what else should go here, open to suggestions. Design contributions, without code, are also acceptable for hacktoberfest.

**Comment by DugarRishab** [comment]
hey @aaronleopold I would like to contribute by assigning some figma designs

**Comment by aaronleopold** [comment]
@DugarRishab sure thing, thanks!

**Comment by hkwiseman** [comment]
Hey, @aaronleopold! I’d like to get involved with the project and could get started on the code for this task

**Comment by aaronleopold** [comment]
Closing tracking for this in favor of #107
