### ISSUE TITLE
How is this different from KavitaReader ?

### ISSUE THREAD

**Issue by alx-xlx** [aaronleopold/stump#58]
will this be similar to Kavitareader ? or different

**Comment by aaronleopold** [comment]
In short: Stump is similar. Of course, at the same time, it will be different 🙂. This goes for Komga, Kavita, and any other digital book media server really. 

Stump started as just a fun side project for me to learn Rust in a context I find fun and constructive.

I don’t know too much about what Kavita can do, so can’t accurately compare it, but the README goes over the goals for the project that I think provides a good overview of what I would eventually like Stump to be. Some highlights:

- Fast, small footprint, low memory consumption 
- Adaptable, allow multiple file system patterns and file format support. 
    - I organize my comics and ebooks differently, so that was important to me. 
- Pretty to look at, easy to use
