### ISSUE TITLE
GH Actions for releases

### ISSUE THREAD

**Issue by aaronleopold** [aaronleopold/stump#70]
If I ever want to make a release, I'll need to have some sort of automated system for doing it. This would honestly be super useful for testing/nightly releases or something, as well. Like #68, I am not very knowledgable in this area.

In general, when a release is made the following needs to happen:
- `server` build
    - linux, macos, windows binaries (this can probably be done at once thanks to [this](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds)
- `web` build
- `desktop` build
    - linux, macos, windows (AppImage, dmg, msi - I think? Unsure what best is for Linux broad support)
- docker `server` build
    - arm, amd64

Some constraints that I have no idea how to go about yet:
- prisma client needs to be generated, cached and shared between rust actions
    - this might be tricky with docker? `include_str!` macros might mess things up but also 🤷
- rust dependencies should be cached (https://github.com/Swatinem/rust-cache)

**Comment by f8thl3ss** [comment]
Hello! I'll give it a try :)

**Comment by aaronleopold** [comment]
Just assigned you, thanks! If you have any questions please let me know 🙂

**Comment by aaronleopold** [comment]
Hey there @f8thl3ss, just merged a few additional changes to `gh-actions` (see #72). Those involved changes to the PR checks, not the release actions for this issue but wanted to let you know in case there are any conflicts 🙂

**Comment by f8thl3ss** [comment]
Thanks for letting me know! :) I've pulled the latest changes.
