### ISSUE TITLE
Don't detect pdf file in root 

### ISSUE THREAD

**Issue by echo-saurav** [aaronleopold/stump#84]
how can i read normal pdf file, no comic with folder structure. It seems like it don't detect any books if i put all my pdf to root folder

**Comment by aaronleopold** [comment]
Hey there, [PDF support](https://github.com/aaronleopold/stump/issues/35) hasn't been implemented yet.

**Comment by echo-saurav** [comment]
ok, guess i need to wait

**Comment by aaronleopold** [comment]
I'll try and make it a bit clearer on the readme regarding what's completed. 

I'll also be adding some sort of automated, changelog system before the first release that would highlight stuff like that.
