### ISSUE TITLE
Setup web-hook for docker hub tag updates

### ISSUE THREAD

**Issue by aaronleopold** [aaronleopold/stump#94]
Seems fairly straight-forward, even a few easy library choices:

https://www.npmjs.com/package/dockerhub-webhook

- Needs to be hostable at a domain, I am not opening up my network for this
- Can start as just docker hub, but should be agnostic enough to maybe handle other sources to feed into discord

**Comment by azais-corentin** [comment]
I believe this could all be done automatically on every push and without a domain, using github actions.

Here are some examples of existing setups that work with either the docker registry or the github container registry:
https://github.com/AnalogJ/scrutiny/blob/master/.github/workflows/docker-nightly.yaml
https://github.com/grocy/grocy-docker/blob/main/.github/workflows/publish.yml
https://github.com/jesec/flood/blob/master/.github/workflows/publish-rolling.yml
https://github.com/ajnart/homarr/blob/dev/.github/workflows/docker_dev.yml
https://github.com/qdm12/gluetun/blob/master/.github/workflows/ci.yml

**Comment by aaronleopold** [comment]
Thanks for the references! You're probably right, using an action is probably the way to go here. A quick search and I see https://github.com/Ilshidur/action-discord

**Comment by aaronleopold** [comment]
So this will _eventually_ change a little, but just for nightly tags this is good!
